sudo: false
language: node_js
node_js:
  - "7"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
before_install:
  - uname -a
install:
  - CC=gcc-5 CXX=g++-5 npm install

script:
  - npm test