sudo: false
language: node_js
node_js:
  - "7"

branches:
  only:
    - master

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

before_install:
  - uname -a

install:
  - cd $TRAVIS_BUILD_DIR/nodejs/server && CC=gcc-5 CXX=g++-5 npm install

script:
  - cd $TRAVIS_BUILD_DIR/nodejs/server && npm test