---
- name: Upgrade
  debug:
    msg: "Upgrading from 9.4 to {{ pg_version }}"

- name: Stop PostgreSQL 9.4
  service:
    name: postgresql
    state: stopped
    args: 9.4

- name: Drop empty cluster
  become: yes
  become_user: postgres
  shell: "pg_dropcluster {{ pg_version }} main --stop"
  environment:
    LANG: "en_US.UTF-8"

- name: Upgrade 9.4 cluster
  become: yes
  become_user: postgres
  shell: "pg_upgradecluster 9.4 main"
  environment:
    LANG: "en_US.UTF-8"

- name: Drop unnecessary 9.4 cluster
  become: yes
  become_user: postgres
  shell: "pg_dropcluster 9.4 main"
  environment:
    LANG: "en_US.UTF-8"

- name: Uninstall PostgreSQL 9.4
  apt:
    pkg: "{{ item }}"
    state: absent
  with_items:
    - postgresql-9.4
    - postgresql-client-9.4